-- MySQL Script generated by MySQL Workbench
-- sex 23 nov 2018 19:53:34 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema financial
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `financial` ;

-- -----------------------------------------------------
-- Schema financial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `financial` DEFAULT CHARACTER SET utf8 ;
USE `financial` ;

-- -----------------------------------------------------
-- Table `financial`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `financial`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `financial`;
INSERT INTO `user` (`user_id`, `name`, `username`, `password`) VALUES (1, 'Adriano', 'adriano', '123');
COMMIT;
